# Generated by Django 5.1.1 on 2024-09-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='defaults/product-1.jpg', upload_to='product/'),
        ),
    ]
